### ISSUE TITLE
SQL Alchemy 2.0 support

### ISSUE THREAD

**Issue by caryfitzhugh** [mcfunley/pugsql#68]
AttributeError: 'Engine' object has no attribute 'execute'

Recent breaking change on SQLAlchemy 2.0 
https://stackoverflow.com/questions/75316741/attributeerror-engine-object-has-no-attribute-execute-when-trying-to-run-sq

**Comment by mcfunley** [comment]
This should be working in 0.3.0!
